enforce_secure_profile: false
listeners:
- query_port: 25577
  motd: '&8&l| &athealzhe.ga &8&l» &a1.19.X'
  tab_list: SERVER
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    localhost: hub
    thealzhe.ga: hub
  ping_passthrough: false
  priorities:
  - hub
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  tech:
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
  - minecraft.command.op
  - minecraft.command.deop
log_pings: false
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: e5ac5b74-fce7-42e2-b5e7-833ca6bd86a4
player_limit: -1
ip_forward: true
groups:
  Alzhe:
  - tech
  mhlAlzhe:
  - tech
  thealzhe:
  - tech
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: true
prevent_proxy_connections: false
online_mode: true
forge_support: false
disabled_commands:
- plugins
- version
servers:
  hub:
    motd: '&8&l| &athealzhe.ga &8&l» &a1.19.X'
    address: localhost:25566
    restricted: false
  survie:
    motd: '&8&l| &athealzhe.ga &8&l» &a1.19.X'
    address: localhost:25567
    restricted: false
